# Generated by Django 4.2.3 on 2023-07-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='name')),
                ('descriptions', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('trade', models.BooleanField(help_text='If you wanna trade', verbose_name='trade')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Update date')),
            ],
        ),
    ]
