# Generated by Django 4.2.3 on 2023-08-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_alter_advertisement_options_advertisement_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
